HISTORICAL_DAYS = 730
CHART_WINDOW_BARS = 70

BULL_COLOR = "green"
BEAR_COLOR = "black"

CANDLE_WIDTH = 0.50
WICK_LINE_WIDTH = 0.50
CANDLE_ALPHA = 0.90

# Bigger value = candles with tiny bodies look less like dashes.
MIN_CANDLE_BODY_RATIO = 0.008

# Bigger value = taller volume bars.
VOLUME_BAND_RATIO = 0.40
VOLUME_GAP_RATIO = 0.04
VOLUME_ALPHA = 0.32

# Settings constants
ALPACA_API_KEY = "ALPACA_API_KEY"
ALPACA_SECRET_KEY = "ALPACA_SECRET_KEY"
ALPACA_DATA_FEED = "ALPACA_DATA_FEED"
DATA_FEED_IEX = "iex"
DATA_FEED_SIP = "sip"
