from __future__ import annotations

from pathlib import Path

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.backends.backend_pdf import PdfPages

from market_terminal.strategies import StrategySpec


def _fmt_pct(value: float) -> str:
    return "—" if pd.isna(value) else f"{value:.2%}"


def _fmt_num(value: float) -> str:
    return "—" if pd.isna(value) else f"{value:.2f}"


def _formatted_report_table(metrics: pd.DataFrame) -> pd.DataFrame:
    columns = [
        "Total Return",
        "CAGR",
        "Volatility",
        "Sharpe Ratio",
        "Sortino Ratio",
        "Maximum Drawdown",
        "Win Rate",
        "Trades",
    ]
    table = metrics[[col for col in columns if col in metrics.columns]].copy()

    for col in ["Total Return", "CAGR", "Volatility", "Maximum Drawdown", "Win Rate"]:
        if col in table.columns:
            table[col] = table[col].map(_fmt_pct)

    for col in ["Sharpe Ratio", "Sortino Ratio"]:
        if col in table.columns:
            table[col] = table[col].map(_fmt_num)

    return table


def _best_strategy_text(metrics: pd.DataFrame) -> str:
    tradable = metrics.drop(index=["Buy & Hold"], errors="ignore")

    if tradable.empty or "Sharpe Ratio" not in tradable.columns:
        return "No strategy Sharpe ratio was available to rank risk-adjusted performance."

    sharpe = tradable["Sharpe Ratio"].dropna()

    if sharpe.empty:
        return "No strategy produced a valid Sharpe ratio, so risk-adjusted ranking is inconclusive."

    best = sharpe.idxmax()
    value = sharpe.loc[best]
    return f"On this sample, the best risk-adjusted strategy by Sharpe ratio was: {best} (Sharpe {value:.2f})."


def create_pdf_report(
    ticker: str,
    years: int,
    data: pd.DataFrame,
    metrics: pd.DataFrame,
    strategy_specs: list[StrategySpec],
    chart_paths: list[Path],
    output_path: Path,
) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with PdfPages(output_path) as pdf:
        fig = plt.figure(figsize=(11, 8.5))
        fig.text(0.08, 0.90, "Technical Indicators & Strategy Backtesting", fontsize=22, weight="bold")
        fig.text(0.08, 0.84, f"Ticker: {ticker.upper()}", fontsize=14)
        fig.text(0.08, 0.80, f"Data window: approximately {years} years of daily OHLCV data", fontsize=12)

        if not data.empty:
            start = data.index.min().strftime("%Y-%m-%d")
            end = data.index.max().strftime("%Y-%m-%d")
            fig.text(0.08, 0.76, f"Observed range: {start} to {end} ({len(data):,} bars)", fontsize=12)

        objective = (
            "Objective: evaluate buy-and-hold, trend-following, mean-reversion, "
            "and custom multi-indicator strategies on both absolute and risk-adjusted performance."
        )
        fig.text(0.08, 0.68, objective, fontsize=11, wrap=True)
        fig.text(0.08, 0.60, _best_strategy_text(metrics), fontsize=12, weight="bold", wrap=True)
        fig.text(
            0.08,
            0.50,
            "Backtest assumptions: $100,000 initial capital, long-only, no leverage, no short selling, "
            "whole-share position sizing, and next-open execution after a close-based signal.",
            fontsize=11,
            wrap=True,
        )
        fig.text(0.08, 0.10, "Generated by run_backtest.py", fontsize=9)
        plt.axis("off")
        pdf.savefig(fig)
        plt.close(fig)

        table = _formatted_report_table(metrics)
        fig, ax = plt.subplots(figsize=(11, 8.5))
        ax.axis("off")
        ax.set_title("Performance Comparison", fontsize=18, pad=20)
        rendered_table = ax.table(
            cellText=table.values,
            rowLabels=table.index,
            colLabels=table.columns,
            cellLoc="center",
            loc="center",
        )
        rendered_table.auto_set_font_size(False)
        rendered_table.set_fontsize(8)
        rendered_table.scale(1.0, 1.7)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        fig = plt.figure(figsize=(11, 8.5))
        y = 0.94
        fig.text(0.06, y, "Strategy Rules", fontsize=18, weight="bold")
        y -= 0.07

        for spec in strategy_specs:
            fig.text(0.06, y, spec.name, fontsize=13, weight="bold")
            y -= 0.035
            fig.text(0.08, y, spec.description, fontsize=9.5, wrap=True)
            y -= 0.06
            fig.text(0.08, y, "Entry:", fontsize=10, weight="bold")
            y -= 0.03
            for rule in spec.entry_rules:
                fig.text(0.10, y, f"• {rule}", fontsize=9, wrap=True)
                y -= 0.028
            fig.text(0.08, y, "Exit:", fontsize=10, weight="bold")
            y -= 0.03
            for rule in spec.exit_rules:
                fig.text(0.10, y, f"• {rule}", fontsize=9, wrap=True)
                y -= 0.028
            y -= 0.035

            if y < 0.18:
                plt.axis("off")
                pdf.savefig(fig)
                plt.close(fig)
                fig = plt.figure(figsize=(11, 8.5))
                y = 0.94

        plt.axis("off")
        pdf.savefig(fig)
        plt.close(fig)

        for chart_path in chart_paths:
            if not chart_path.exists():
                continue

            img = mpimg.imread(chart_path)
            fig, ax = plt.subplots(figsize=(11, 8.5))
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(chart_path.stem.replace("_", " ").title(), fontsize=14)
            pdf.savefig(fig, bbox_inches="tight")
            plt.close(fig)

        fig = plt.figure(figsize=(11, 8.5))
        fig.text(0.08, 0.90, "Discussion", fontsize=18, weight="bold")
        fig.text(0.08, 0.82, _best_strategy_text(metrics), fontsize=12, wrap=True)
        fig.text(
            0.08,
            0.72,
            "Interpretation notes: Buy & Hold is the passive benchmark. Trend-following should generally do well "
            "during persistent uptrends but can lag in choppy regimes. Mean-reversion can perform well after sharp "
            "oversold moves but may suffer when selloffs continue. The custom strategy attempts to reduce false "
            "signals by requiring trend, momentum, volatility-location, and volume confirmation.",
            fontsize=11,
            wrap=True,
        )
        fig.text(
            0.08,
            0.55,
            "Limitations: This simple engine does not model taxes, bid/ask spread, partial fills, market impact, "
            "borrow constraints, or exchange fees unless a commission is provided. Results should be treated as "
            "research output, not a live-trading recommendation.",
            fontsize=11,
            wrap=True,
        )
        plt.axis("off")
        pdf.savefig(fig)
        plt.close(fig)

    return output_path
